AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 5
Resources:
  GeographyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://codefordenver/f60b0ece7871d474d035f17f7e6f9fb7
      Handler: geography
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /geography/{geounit}/{year}
            Method: GET
  CensusAcs5Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://codefordenver/05f7f664725fc6aef5a0d53833229563
      Handler: census_acs5
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /census/acs5/{subject}/{geounit}/{year}
            Method: GET
Outputs:
  ShiftAPIServerlessFunctions:
    Description: API Gateway endpoint URL for Prod environment
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/
