AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SHIFT-API
Resources:
  APIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/api
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /
            Method: get