AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  
  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  GeographyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: geography/
      Handler: geography
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /geography/{geounit}/{year}
            Method: GET
            Request:
              Parameters:
                Paths:
                  geounit: true
                  year: true

  ApiFunctions:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: api
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: "foobar"


Outputs:
  ShiftAPIServerlessFunctions:
    Description: "API Gateway endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/"

  ApiFunctions:
    Description: "SHIFT-API for interacting with Open Data"
    Value: !GetAtt ApiFunctions.Arn

  ApiFunctionsIamRole:
    Description: "Implicit IAM Role created for Shift API function"
    Value: !GetAtt ApiFunctionsRole.Arn
