version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    environment:
      GO111MODULE: "on"
      GOPATH: "/home/circleci/go"
      USER: circleci
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8

    # directory where steps are run. Path must conform to the Go Workspace requirements
    working_directory: ~/go/src/github.com/codefordenver

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory

      # Normally, this step would be in a custom primary image;
      # we've added it here for the sake of explanation.
      - run: sudo apt-get install build-essential
      - run: make deps
      # - run: ./ci/scripts/install-linuxbrew.sh
      # - run: echo 'export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"' >> $BASH_ENV 
      # - run: brew tap aws/tap
      # - run: brew update
      # - run: brew install aws-sam-cli
      - run: sudo apt install curl
      - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - run: sudo python get-pip.py
      - run: sudo apt-get install libffi-dev libssl-dev libpython2.7-dev
      - run: echo $PWD
      - run: git clone git@github.com:awslabs/aws-sam-cli.git
      - run: pip install --user -e aws-sam-cli/.

#      - save_cache: # Store cache in the /go/pkg directory
#          key: v1-pkg-cache
#          paths:
#            - "/go/pkg"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - CHORE-21